### ISSUE TITLE
NPM install fails behind corporate proxy

### ISSUE THREAD

**Issue by lafe** [OfficeDev/office-ui-fabric-js#112]
When I try to run the `npm install` command to get the demo running, I get the following issue behind our corporate proxy:
```
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:100:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:185:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:850:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
npm WARN addRemoteGit     at emitOne (events.js:90:13)
npm WARN addRemoteGit     at Socket.emit (events.js:182:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:484:12)
npm WARN addRemoteGit  git://github.com/colynb/commonjs-html-prettyprinter.git resetting remote C:\Users\Reihnold\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-82a62197 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Reihnold\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/colynb/commonjs-html-prettyprinter.git C:\Users\Reihnold\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-82a62197: Cloning into bare repository 'C:\Users\Reihnold\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-82a62197'...
npm ERR! git clone --template=C:\Users\Reihnold\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/colynb/commonjs-html-prettyprinter.git C:\Users\Reihnold\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-82a62197: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\Reihnold\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/colynb/commonjs-html-prettyprinter.git C:\Users\Reihnold\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-82a62197: github.com[0: 192.30.253.112]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code 128
npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Reihnold\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/colynb/commonjs-html-prettyprinter.git C:\Users\Reihnold\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-82a62197
npm ERR! Cloning into bare repository 'C:\Users\Reihnold\AppData\Roaming\npm-cache\_git-remotes\git-github-com-colynb-commonjs-html-prettyprinter-git-82a62197'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=No error
```
The problem is that gulp-html-prettify references a Git repository directly using the git:// protocol (see https://github.com/colynb/gulp-html-prettify/blob/master/package.json). Unfortunately, the git:// protocol may be blocked by corporate proxies (as is the case with our proxy), therefore the installation fails.

**Comment by lafe** [comment]
[This comment](https://github.com/npm/npm/issues/5257#issuecomment-60441477) had the solution for my specific problem:
* Create a rewrite of the "git://" and "git@" protocols
* Make sure that the change is available in all .gitconfig files

However, this might be included in the documentation, as this is the first project I encountered that had this issue (after two years of web development in the same environment).

**Comment by ericthompson** [comment]
Thanks for filing this, @lafe - we haven't seen this before, but I'm glad you raised it.

We're going to look into using a different gulp plugin as the [gulp-html-prettify project](https://github.com/colynb/gulp-html-prettify) doesn't seem to be too active.

**Comment by kenhansen01** [comment]
Running the following commands resolved this error for me:

git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://

It points git to https rather than git
